using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RPG_Battle_Engine
{
    public class EndBattleEffect : IBattleEffect
    {
        public Guid Guid { get; init; }
        /// <summary>
        /// Target is the GUID of the Player that won the battle
        /// </summary>
        public Guid Target { get; init; }
        /// <summary>
        /// Source is an Empty GUID, because this is autogenerated and has no Target.
        /// </summary>
        public Guid Source { get; init; }

        public EndBattleEffect(Guid target, Guid? guid = null)
        {
            Guid = guid ?? Guid.NewGuid();
            Target = target;
            Source = Guid.Empty;
        }

        public BattleState TakeEffect(BattleState currentState)
        {
            // TODO: End Battle Stuff. I don't know how Im going to do that yet.
            throw new NotImplementedException();
        }


        public override string ToString()
        {
            return "End Battle Effect";
        }
    }
}
